name: Build & deploy Python Scraper - Dev

on: workflow_dispatch

jobs:
    build:
        runs-on: [self-hosted, "ARM64", "Linux", "dev1"]

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: "Build docker image"
              run: docker compose build

            - name: "Stop and remove docker container"
              run: docker stop strava_api_service || true && docker rm strava_api_service || true

            - name: "Run docker container"
              run: docker compose up -d
